version: '3.7'
services:
    laravel-nginx:
        container_name: 'laravel-nginx'
        image: nginx:1.24.0
        ports:
            - "8081:80"
        volumes:
            - ./nginx/laravel.base/laravel-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/laravel
        working_dir: /var/www/laravel
        links:
            - php-fpm-laravel

    php-fpm-laravel:
        container_name: 'php-fpm-laravel'
        build:
            context: php
            dockerfile: Dockerfile
        ports:
            - 9091:9000
        volumes:
            - ./:/var/www/laravel
        links:
            - laravel-mysql

    laravel-mysql:
        image: mysql:5.7
        container_name: "laravel-mysql"
        platform: linux/amd64
        ports:
            - "33061:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel








